# Generated by Django 2.2.4 on 2019-08-25 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeID', models.CharField(max_length=30)),
                ('lastseen', models.DateTimeField(blank=True, null=True)),
                ('status_sent', models.DateTimeField(blank=True, null=True)),
                ('isGateway', models.BooleanField(blank=True, default=False)),
                ('notification_sent', models.BooleanField(default=False)),
                ('status', models.CharField(default=' ', help_text='C is current, X is down, M in maintenance mode', max_length=1)),
                ('textStatus', models.CharField(blank=True, max_length=10, null=True)),
                ('nextUpdate', models.DateTimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('descr', models.TextField(blank=True, null=True)),
                ('lastData', models.TextField(blank=True, null=True)),
                ('lastStatus', models.TextField(blank=True, null=True)),
                ('allowedDowntime', models.IntegerField(default=60, help_text="Minutes that the node can be 'unheard' before being marked as Offline")),
                ('hardware', models.CharField(blank=True, max_length=50, null=True)),
                ('software', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('battName', models.CharField(blank=True, help_text='The attribute name in JSON messages used for battery levels', max_length=40, null=True)),
                ('battMonitor', models.BooleanField(default=False)),
                ('battLevel', models.FloatField(default=0.0)),
                ('battWarn', models.FloatField(default=0.0, help_text='The battery level, below which warning message are generated')),
                ('battCritical', models.FloatField(default=0.0, help_text='The battery level, below which critical warning message are generated')),
                ('RSSI', models.FloatField(default=0.0)),
                ('portal', models.URLField(blank=True, help_text='A link where more data on this node is available', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=50)),
                ('descr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('reportType', models.CharField(blank=True, default='S', max_length=1, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NodeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(blank=True, default=False)),
                ('sms', models.BooleanField(blank=True, default=False)),
                ('lastemail', models.DateTimeField(blank=True, null=True)),
                ('lastsms', models.DateTimeField(blank=True, null=True)),
                ('smsSent', models.BooleanField(blank=True, default=False)),
                ('nodeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.Team'),
        ),
    ]
