# Generated by Django 2.2.1 on 2019-05-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeID', models.CharField(max_length=30)),
                ('lastseen', models.DateTimeField(blank=True, null=True)),
                ('statusSent', models.DateTimeField(blank=True, null=True)),
                ('isGateway', models.BooleanField(blank=True, default=False)),
                ('notificationSent', models.BooleanField(blank=True, default=False)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('nextUpdate', models.DateTimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
