# Generated by Django 2.2.1 on 2019-05-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20190516_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='message_delay',
            field=models.FloatField(blank=True, help_text='Minutes the node can be inactive without being considered down', null=True),
        ),
        migrations.AddField(
            model_name='nodeuser',
            name='lastemail',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodeuser',
            name='lastsms',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodeuser',
            name='smsSent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
