# Generated by Django 2.2.1 on 2019-05-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20190516_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='hardware',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='software',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
