# Generated by Django 2.2.2 on 2019-06-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_nodeuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeuser',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
