# Generated by Django 2.2.2 on 2019-06-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_nodeuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeuser',
            name='username',
        ),
    ]
