# Generated by Django 2.2.1 on 2019-05-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20190517_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='message_delay',
            field=models.FloatField(default=60, help_text='Minutes the node can be inactive without being considered down'),
        ),
    ]
