# Generated by Django 2.2.2 on 2019-06-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20190517_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=50)),
                ('descr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='node',
            old_name='statusSent',
            new_name='status_sent',
        ),
        migrations.RemoveField(
            model_name='node',
            name='message_delay',
        ),
        migrations.RemoveField(
            model_name='node',
            name='notificationSent',
        ),
        migrations.AddField(
            model_name='node',
            name='RSSI',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='allowedDowntime',
            field=models.IntegerField(default=60, help_text="Minutes that the node can be 'unheard' before being marked as Offline"),
        ),
        migrations.AddField(
            model_name='node',
            name='battCritical',
            field=models.FloatField(default=0.0, help_text='The battery level, below which critical warning message are generated'),
        ),
        migrations.AddField(
            model_name='node',
            name='battLevel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='battMonitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='battName',
            field=models.CharField(blank=True, help_text='The attribute name in JSON messages used for battery levels', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='battWarn',
            field=models.FloatField(default=0.0, help_text='The battery level, below which warning message are generated'),
        ),
        migrations.AddField(
            model_name='node',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='textStatus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(default=' ', help_text='C is current, X is down, M in maintenance mode', max_length=1),
        ),
        migrations.AlterField(
            model_name='node',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.Team'),
        ),
    ]
