# Generated by Django 2.2.1 on 2019-06-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20190531_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='battCritical',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='battName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='battValue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='node',
            name='battWarning',
            field=models.FloatField(default=0.0),
        ),
    ]
