# Generated by Django 2.2.2 on 2019-06-22 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20190622_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodeuser',
            old_name='username',
            new_name='user',
        ),
    ]
