# Generated by Django 2.2.1 on 2019-06-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20190604_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='textStatus',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(default=' ', help_text='C is current, X is down, M in maintenance mode', max_length=1),
        ),
    ]
