# Generated by Django 2.2.1 on 2019-06-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20190604_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='message_delay',
        ),
        migrations.AddField(
            model_name='node',
            name='allowedDowntime',
            field=models.IntegerField(default=60, help_text="Minutes that the node can be 'unheard' before being marked as Offline"),
        ),
    ]
