# Generated by Django 2.2.1 on 2019-06-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20190604_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='notificationSent',
        ),
        migrations.AddField(
            model_name='node',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
