# Generated by Django 2.2.2 on 2019-06-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20190606_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='battWarning',
            new_name='battWarn',
        ),
        migrations.AddField(
            model_name='node',
            name='battMonitor',
            field=models.BooleanField(default=False),
        ),
    ]
