# Generated by Django 2.2.2 on 2019-06-17 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20190606_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=50)),
                ('descr', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.Team'),
        ),
    ]
