# Generated by Django 2.2.2 on 2019-06-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_auto_20190617_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
