# Generated by Django 2.2.2 on 2019-06-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_auto_20190617_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='RSSI',
            field=models.FloatField(default=0.0),
        ),
    ]
